# Testing unsupervised machine learning algorithms

In [47]:
import numpy as np
import pandas as pd
from load_data import LoadData
from sklearn.utils import shuffle

In [48]:
data = LoadData(15)

In [49]:
df = data.load_data()
df = shuffle(df)
print(df.shape)
df.head()

no image
(224, 4)


blue  green  red  label
180     1     76  222      1
176   164     78   90     12
113   117    182   43      8
100   205    144   70     10
62      0    165  254      2

In [50]:
from sklearn.cross_validation import train_test_split
X = np.array(df.drop(['label'],axis=1))
y = np.array(df['label'])
X_train, X_test, y_train, y_test = train_test_split(X, y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape
y_test

array([10,  8, 11,  2, 13, 14, 11,  3,  5,  6, 11,  3,  7, 10,  0, 10,  0,
       11,  5,  9,  3, 14,  3,  1,  5, 10,  4, 12,  2,  7,  1,  2,  4,  9,
        8, 12, 12, 12,  6,  0, 14,  2,  9,  8,  6, 11, 10,  3,  5, 12,  4,
        3,  8, 10, 13,  5])

In [51]:
from sklearn.cluster import KMeans
clf = KMeans(n_c)
clf.fit(X_train)
clf.cluster_centers_

array([[182.        ,  21.625     ,  65.625     ],
       [ 28.16666667, 215.        , 174.41666667],
       [ 98.44444444, 173.        ,  17.77777778],
       [ 33.875     ,  24.8125    , 225.625     ],
       [ 21.1875    , 185.3125    , 250.25      ],
       [185.26666667, 179.        ,   3.66666667],
       [  3.375     , 168.5       ,  26.625     ],
       [162.05263158,  76.26315789,  80.47368421],
       [ 28.        ,  98.61538462, 241.38461538],
       [ 71.53333333, 177.6       ,  61.93333333],
       [202.        , 142.25      ,  58.375     ],
       [ 58.85714286, 196.85714286, 132.28571429],
       [130.76923077,  32.92307692,  60.76923077],
       [227.75      ,  56.75      ,  19.5       ],
       [  5.8       , 236.4       , 242.2       ]])

In [52]:
clf.labels_

array([ 4,  0,  7, 12,  5, 10,  2,  8,  9,  9,  9,  3, 12, 14,  3,  0,  9,
        1,  8,  4,  0,  9,  7, 14,  4,  1, 10,  7,  4,  8, 10, 12, 12,  6,
        5,  7,  7,  9, 12, 14,  6,  1,  7, 10,  7, 11,  7,  4,  5,  7,  3,
        8,  5, 11,  3, 12,  7, 12,  4,  5,  1, 11,  0,  7,  8,  2, 12,  3,
        0,  6,  9,  1, 12,  3, 14,  6,  2,  9,  2,  4,  5,  9,  7,  6,  6,
       13,  7,  0,  5,  3,  2,  7,  2,  8,  3, 10,  3,  4, 11,  0,  4, 12,
        7,  9,  6,  3,  5,  4,  4,  3, 13, 12,  2,  0,  8,  1, 10,  9,  8,
        3,  7, 11,  5,  4, 10,  4,  5, 12,  9,  5,  5, 14,  4,  2,  7,  3,
        1, 13,  1,  3,  8, 10,  8,  1,  1,  8,  3,  2,  5,  9, 13,  8,  5,
        8,  7,  4,  6,  9,  1, 12,  3,  5,  7,  9,  1,  4, 11, 11])

In [55]:
y_pred = clf.predict(X_test)
print(y_pred.shape)
for i in range(len(y_pred)):
    print('Pred:{} real:{}'.format(y_pred[i],y_test[i]))

(56,)
Pred:5 real:10
Pred:2 real:8
Pred:7 real:11
Pred:8 real:2
Pred:12 real:13
Pred:12 real:14
Pred:7 real:11
Pred:14 real:3
Pred:11 real:5
Pred:1 real:6
Pred:13 real:11
Pred:14 real:3
Pred:6 real:7
Pred:5 real:10
Pred:3 real:0
Pred:10 real:10
Pred:3 real:0
Pred:13 real:11
Pred:11 real:5
Pred:10 real:9
Pred:14 real:3
Pred:12 real:14
Pred:14 real:3
Pred:8 real:1
Pred:11 real:5
Pred:13 real:10
Pred:14 real:4
Pred:7 real:12
Pred:4 real:2
Pred:9 real:7
Pred:8 real:1
Pred:4 real:2
Pred:14 real:4
Pred:5 real:9
Pred:2 real:8
Pred:7 real:12
Pred:13 real:12
Pred:7 real:12
Pred:9 real:6
Pred:3 real:0
Pred:12 real:14
Pred:4 real:2
Pred:5 real:9
Pred:2 real:8
Pred:9 real:6
Pred:7 real:11
Pred:10 real:10
Pred:14 real:3
Pred:11 real:5
Pred:0 real:12
Pred:14 real:4
Pred:14 real:3
Pred:2 real:8
Pred:10 real:10
Pred:12 real:13
Pred:14 real:5
